import { getDatabase, ref, set } from 'firebase/database';
import { db } from './service';
import { addDoc, collection } from 'firebase/firestore';

export const data = [
  {
    courseCode: 'COMP1511',
    courseName: 'Programming Fundamentals',
    assessmentItems: [
      {
        assName: 'Problem sets',
        weight: 15,
        startWeek: 2,
        endWeek: 10,
        dueDate: '17/11/2023',
        status: 'ongoing',
        isWeekly: true,
        dueDay: 4,
      },
      {
        assName: 'Assignment 1',
        weight: 20,
        startWeek: 4,
        endWeek: 7,
        dueDate: '17/10/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Assignment 2',
        weight: 25,
        startWeek: 7,
        endWeek: 10,
        dueDate: '17/11/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Final Exam',
        weight: 40,
        startWeek: 1,
        endWeek: 11,
        dueDate: '30/10/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
    ],
    progress: 30,
    totalCourseMark: 25,
  },
  {
    courseCode: 'COMP1521',
    courseName: 'Computer Systems Fundamentals',
    assessmentItems: [
      {
        assName: 'Labs',
        weight: 15,
        startWeek: 3,
        endWeek: 10,
        dueDate: '17/11/2023',
        status: 'ongoing',
        isWeekly: true,
        dueDay: 3,
      },
      {
        assName: 'Tests',
        weight: 10,
        startWeek: 3,
        endWeek: 10,
        dueDate: '17/10/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Assignment 1',
        weight: 30,
        startWeek: 7,
        endWeek: 10,
        dueDate: '31/10/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Assignment 2',
        weight: 30,
        startWeek: 7,
        endWeek: 10,
        dueDate: '29/10/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Final Exam',
        weight: 45,
        startWeek: 1,
        endWeek: 11,
        dueDate: '24/11/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
    ],
    progress: 30,
    totalCourseMark: 25,
  },
  {
    courseCode: 'COMP1531',
    courseName: 'Software Engineering Fundamentals',
    assessmentItems: [
      {
        assName: 'Individual Project',
        weight: 30,
        startWeek: 11,
        endWeek: 11,
        dueDate: '17/11/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Major Group Project',
        weight: 60,
        startWeek: 2,
        endWeek: 10,
        dueDate: '17/11/2023',
        status: 'ongoing',
        isWeekly: true,
        dueDay: 4,
      },
      {
        assName: 'Labs',
        weight: 10,
        startWeek: 2,
        endWeek: 9,
        dueDate: '10/11/2023',
        status: 'not started',
        isWeekly: true,
        dueDay: 1,
      },
    ],
    progress: 30,
    totalCourseMark: 25,
  },
  {
    courseCode: 'COMP2511',
    courseName: 'Object-Oriented Design & Programming',
    assessmentItems: [
      {
        assName: 'Coursework',
        weight: 15,
        startWeek: 1,
        endWeek: 10,
        dueDate: '15/11/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Final Exam',
        weight: 50,
        startWeek: 11,
        endWeek: 11,
        dueDate: '28/11/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Assignment 1 - Object-Oriented Design',
        weight: 15,
        startWeek: 5,
        endWeek: 5,
        dueDate: '11/10/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Assignment 2 - Refactoring & Design Patterns',
        weight: 20,
        startWeek: 9,
        endWeek: 9,
        dueDate: '8/11/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Final Exam',
        weight: 45,
        startWeek: 11,
        endWeek: 11,
        dueDate: '21/11/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
    ],
    progress: 30,
    totalCourseMark: 25,
  },
  {
    courseCode: 'COMP2521',
    courseName: 'Data Structures and Algorithms',
    assessmentItems: [
      {
        assName: 'Assignment 1 - Trees',
        weight: 15,
        startWeek: 4,
        endWeek: 7,
        dueDate: '24/10/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Assignment 2 - Graphs',
        weight: 15,
        startWeek: 7,
        endWeek: 10,
        dueDate: '15/11/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Labs',
        weight: 15,
        startWeek: 1,
        endWeek: 10,
        dueDate: '17/11/2023',
        status: 'not started',
        isWeekly: true,
        dueDay: 2,
      },
      {
        assName: 'Quizzes',
        weight: 10,
        startWeek: 1,
        endWeek: 10,
        dueDate: '17/11/2023',
        status: 'not started',
        isWeekly: true,
        dueDay: 1,
      },
      {
        assName: 'Final Exam',
        weight: 45,
        startWeek: 11,
        endWeek: 11,
        dueDate: '23/11/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
    ],
    progress: 30,
    totalCourseMark: 25,
  },
  {
    courseCode: 'COMP3121',
    courseName: 'Algorithms and Programming Techniques',
    assessmentItems: [
      {
        assName: 'Take-home quiz',
        weight: 5,
        startWeek: 1,
        endWeek: 7,
        dueDate: '27/10/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Assignment 1',
        weight: 45,
        startWeek: 1,
        endWeek: 3,
        dueDate: '10/11/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Assignment 2',
        weight: 45,
        startWeek: 4,
        endWeek: 6,
        dueDate: '28/10/2023',
        status: 'ongoing',
        isWeekly: false,
        dueDay: 4,
      },
      {
        assName: 'Final Exam',
        weight: 50,
        startWeek: 11,
        endWeek: 11,
        dueDate: '29/11/2023',
        status: 'not started',
        isWeekly: false,
        dueDay: 4,
      },
    ],
    progress: 30,
    totalCourseMark: 25,
  },
  {
    courseCode: 'COMP3900',
    courseName: 'Computer Science Project',
    progress: 30,
    totalCourseMark: 25,
  },
];

export const assessments = [
  {
    assName: 'Problem sets',
    weight: 15,
    startWeek: 2,
    endWeek: 10,
    dueDate: '17/11/2023',
    status: 'ongoing',
    courseCode: 'COMP1511',
  },
  {
    assName: 'Assignment 1',
    weight: 20,
    startWeek: 4,
    endWeek: 7,
    dueDate: '17/10/2023',
    status: 'ongoing',
    courseCode: 'COMP1511',
  },
  {
    assName: 'Assignment 2',
    weight: 25,
    startWeek: 7,
    endWeek: 10,
    dueDate: '17/11/2023',
    status: 'not started',
    courseCode: 'COMP1511',
  },
  {
    assName: 'Final Exam',
    weight: 40,
    startWeek: 1,
    endWeek: 11,
    dueDate: '30/10/2023',
    status: 'not started',
    courseCode: 'COMP1511',
  },
];
